name: project

on:
  push:
    branches: [ master ]

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    
  steps:
  - uses: actions/checkout@v3
  
  - name: Compile CSS and Javascript
    run: |
      npm install
      npm run prod
